trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '*' 
    exclude:
    - 'README.md'

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: NuGetToolInstaller@1
  displayName: "Install latest nuget"
  inputs:
    versionSpec: '>= 5.4.0-0'

- task: NuGetCommand@2
  displayName: "NuGet Pack"
  inputs:
    command: 'custom'
    arguments: 'pack JacobsApps.CleanArchitectureProjectTemplate.CSharp.nuspec -NoDefaultExcludes'

- task: Bash@3
  displayName: "Test nuget package with 'EmptyApi' project type"
  inputs:
    filePath: 'test-nuget-package.sh'
    arguments: 'EmptyApi'

- task: Bash@3
  displayName: "Test nuget package with 'FullApi' project type"
  inputs:
    filePath: 'test-nuget-package.sh'
    arguments: 'FullApi'  

- task: Bash@3
  displayName: "Test nuget package with 'EmptyBlazor' project type"
  inputs:
    filePath: 'test-nuget-package.sh'
    arguments: 'EmptyBlazor'    
  
- task: Bash@3
  displayName: "Test nuget package with 'FullBlazor' project type"
  inputs:
    filePath: 'test-nuget-package.sh'
    arguments: 'FullBlazor' 

- task: Bash@3
  displayName: "Test nuget package with 'EmptyWeb' project type"
  inputs:
    filePath: 'test-nuget-package.sh'
    arguments: 'EmptyWeb'    

- task: Bash@3
  displayName: "Test nuget package with 'FullWeb' project type"
  inputs:
    filePath: 'test-nuget-package.sh'
    arguments: 'FullWeb'    

- task: NuGetCommand@2
  displayName: "NuGet Push"
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.SourcesDirectory)/JacobsApps.CleanArchitectureProjectTemplate.CSharp.*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'
